### PR TITLE
Update CocoaLumberjack to v2.x

### PR DESCRIPTION
**Pull request by jschmid**
I don't know if you are willing to upgrade CocoaLumberjack on this fork. 

We have done it as we are already using the 2.x version on our project and those changes are really lightweight.

### CODE REVIEW

**Comment by Artheyn** [comment]
:+1: 

We need it also. It could be great to merge this PR, thanks :)

**Comment by baoluo** [comment]
Hello @jschmid, I can't merge since travis failed, if you can provide a successful pull request, I'll merge it

**Comment by jschmid** [comment]
Could you please point to the failing build ?

**Comment by baoluo** [comment]
@jschmid, it was displayed under your pull request, but now that I closed it, it disappeared

**Comment by jschmid** [comment]
Well, it was done in https://github.com/robbiehanson/XMPPFramework/pull/665 anyway.

**Comment by baoluo** [comment]
Ok, so we just need to update the pod spec to download the latest xmppframework build

**Comment by mremond** [comment]
Can I help on this ? I am trying to make sure we update to the latest code.
What should I do ?

**Comment by baoluo** [comment]
@mremond Yes you can :) 
The pod 'XMPPFramework' in the pod spec must be updated with the latest build tag from RobbieHanson

**Comment by mremond** [comment]
ok, I guess I need to merge the latest commits as well.
I will give it a try and let you know about the status.

**Comment by baoluo** [comment]
Ok, let me know if you need a bit of coding

**Pull request closed without merging**
